### ISSUE TITLE
Jade processing error

### ISSUE THREAD

**Issue by CoreMetabolicsAdmin** [stormpath/express-stormpath-sample-project#3]
Navigate to /register yields this jade processing error from deep within express-stormpath ...

/usr/local/bin/node server.js
Stormpath Ready
SyntaxError: Unexpected token (1:42)
    at Parser.pp.raise (/Volumes/MCCOY_DATA/NodeDev/express-stormpath-sample-project/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.unexpected (/Volumes/MCCOY_DATA/NodeDev/express-stormpath-sample-project/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2264:8)
    at Parser.pp.parseBindingAtom (/Volumes/MCCOY_DATA/NodeDev/express-stormpath-sample-project/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1876:12)
    at Parser.pp.parseMaybeDefault (/Volumes/MCCOY_DATA/NodeDev/express-stormpath-sample-project/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1920:23)
    at Parser.pp.parseBindingList (/Volumes/MCCOY_DATA/NodeDev/express-stormpath-sample-project/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1896:23)
    at Parser.pp.parseFunctionParams (/Volumes/MCCOY_DATA/NodeDev/express-stormpath-sample-project/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2776:22)
    at Parser.pp.parseFunction (/Volumes/MCCOY_DATA/NodeDev/express-stormpath-sample-project/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2769:8)
    at Parser.pp.parseExprAtom (/Volumes/MCCOY_DATA/NodeDev/express-stormpath-sample-project/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1129:19)
    at Parser.pp.parseExprSubscripts (/Volumes/MCCOY_DATA/NodeDev/express-stormpath-sample-project/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1023:19)
    at Parser.pp.parseMaybeUnary (/Volumes/MCCOY_DATA/NodeDev/express-stormpath-sample-project/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1004:19)

**Comment by robertjd** [comment]
Hi there, it looks like you might have tried this library while we were in the process of updating it to use the latest express-stormpath version.  Can you please let us know if you still have this problem?  Thanks!

**Comment by INCHMAN1900** [comment]
I ran into the same problem while I tried to make a NodeJS program.
still confusing
